name: solomas
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5              #For iOS Native Components
  rxdart: ^0.26.0            #For Simplification of Bloc Streams
  #  connectivity:               ^3.0.6              #Check Internet Connection
  connectivity_plus: ^2.3.6+1            #Check Internet Connection
  permission_handler: ^10.0.0              #Handle Permissions
  geolocator: ^9.0.1              #Get Current Location using _servicesCarnival
  app_settings: ^4.1.8              #Open Native Settings
  shared_preferences: ^2.0.15              #Save Data Locally
  flutter_google_places: ^0.3.0              #Google Places Search
  google_maps_flutter: ^2.1.12              #Google Maps
  fluttertoast: ^8.0.9              #Toasts Messages
  cached_network_image: ^3.2.2              #Cashed Image Display
  #  flutter_webview_plugin:     ^0.4.0             #In-App Web View
  webview_flutter: ^3.0.4
  http: ^0.13.5             #Api Request
  image_picker: ^0.8.5+3             #Pick Image from Gallery Or Camera
  image_cropper: ^3.0.0              #Crop Image
  dio: ^4.0.6              #Upload Image to Amazon Server
  #  apple_sign_in:              ^0.1.0              #Apple Auth Login
  the_apple_sign_in: ^1.1.1
  #  geocoder:                   ^0.2.1              #Google Address Converter
  geocoding: ^2.0.5
  firebase_messaging: ^14.1.2            #For FireBase Notifications
  intl: ^0.17.0             #for DATE Format
  google_sign_in: ^5.4.1             #Google Login
  #flutter_login_facebook:     ^1.6.0             #Facebook Login
  firebase_crashlytics: ^3.0.6              #Firebase Crashes
  #  device_info:                ^2.0.2              #Get iOS version For Apple Sign In
  device_info_plus: ^4.1.2
  #  flutter_xlider:             ^3.2.0              #Distance Seek Bar
  another_xlider: ^1.1.2
  #  flutter_slidable:           ^0.6.0             #Slide to Delete
  flutter_slidable: ^0.6.0             #Slide to Delete
  photo_view: ^0.14.0             #Full Photo Viewer
  #  flutter_local_notifications: ^6.1.1            #Create Local Notification Banner
  flutter_local_notifications: ^12.0.3            #Create Local Notification Banner
  #  keyboard_visibility:        ^0.5.6              #Detect Keyboard Visibility
  flutter_keyboard_visibility: ^5.3.0
  introduction_screen: ^2.1.0             #First Time App Introduction
  dots_indicator: ^2.1.0            #Introduction Screen Dot Indicator
  jwt_decoder: ^2.0.1             #JSON WEB TOKEN DECODER
  #  advance_pdf_viewer:         ^2.0.1             #Pdf Viewer
  syncfusion_flutter_pdfviewer: ^20.2.49-beta
  firebase_core: ^2.3.0            #Flutter core
  socket_io_client: ^2.0.0              #Socket.io for Chat
  url_launcher: ^6.1.5              #Launch Url in external browser
  sign_in_with_apple: ^4.1.0              #sign in with apple
  flutter_linkify: ^5.0.2
  share_plus: ^4.0.10+1
  google_place: ^0.4.7
  carousel_slider: ^4.1.1
  multi_image_picker2: ^5.0.2
  path_provider: ^2.0.11
  firebase_dynamic_links: ^5.0.7
  multi_select_flutter: ^4.1.2
  platform: ^3.1.0
  google_api_headers: ^1.3.0
  package_info_plus_web: ^2.0.0
  flutter_svg: ^1.1.4
  video_player: ^2.4.7
  video_editor: ^1.4.3
  helpers: ^1.1.4
  scroll_to_index: ^3.0.1
  flutter_exit_app: ^1.0.5
  scrollable_positioned_list: ^0.3.5
  vector_math: any
  pinch_zoom: ^1.0.0
  flutter_native_splash: ^2.2.16
  file_picker: ^5.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#ffffff"
  image: assets/image/splash.png
  fill: true
  android: true
  color_dark: "#000000"
  image_dark: assets/image/splash.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Roboto-Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Roboto-Medium
      fonts:
        - asset: fonts/Roboto-Medium.ttf



  assets:
    - assets/images/
    - assets/image/
    - assets/icons/
    - images/

  uses-material-design: true
