import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class SoloColor {
  static Color lightGrey = Color(0xffe8e8e8);
  static Color blueAssent = Color(0xFF27AAE1);
  static Color black = Color(0xFF000000);
  static Color smokeBlack = Color(0xFF292D32);
  static Color jet = Color(0xFF363636);
  static Color graniteGray = Color(0xFF5f5f5f);
  static Color davyGrey = Color(0xFF575757);
  static Color sonicSilver = Color(0xFF777777);
  static Color taupeGray = Color(0xFF878787);
  static Color spanishGray = Color(0xFF979797);
  static Color spanishLightGrey = Color(0xFF9b9b9b);
  static Color silverSand = Color(0xFFc6c6c6);
  static Color philippineSilver = Color(0xFFb4b4b4);
  static Color gainsBoro = Color(0xFFDDDBDC);
  static Color cultured = Color(0xFFF5F3F4);
  static Color white = Color(0xFFffffff);
  static Color lotion = Color(0xFFfbfbfb);
  static Color brightGray = Color(0xFFececec);
  static Color flashWhite = Color(0xFFF5F3F4);
  static Color lightSilver = Color(0xFFD8D8D8);
  static Color blueWhite = Color(0xFFd7ebf2);
  static Color waterBlue = Color(0xFFc9e9f6);
  static Color chargeBlue = Color(0xFF23AAE1);
  static Color blue = Color(0xFF2faadf);
  static Color denimBlue = Color(0xFF204dae);
  static Color purple = Color(0xFF5A21EE);
  static Color middleBluePurple = Color(0xFF8668af);
  static Color darkPink = Color(0xFFCA5BC8);
  static Color lemon = Color(0xFFE1C723);
  static Color lightYellow = Color(0xFFF5F3F4);
  static Color yellowStar = Color(0xFFFFCC48);
  static Color pastelOrange = Color(0xFFfaaf4c);
  static Color orange = Color(0xFFf59629);
  static Color yellow = Color(0xFFf8b86a);
  static Color darkBrown = Color(0xFFD38B5A);
  static Color sunsetRed = Color(0xFFf05360);
  static Color pink = Color(0xFFEE2A7B);
  static Color mediumSeaGreen = Color(0xFF38a956);
  static Color lightGreen = Color(0xFF5AD3A8);
  static Color red = Color(0xFFff0000);
  static Color platinum = Color(0xFFE5E5E5);
  static Color lightGrey200 = Color(0xFF969696);
  static Color electricPink = Color(0xFFEE2A7B);
  static Color batteryChargedBlue = Color(0xFF27AAE1);
  static Color trans = Colors.transparent;
}
